language: ruby
rvm:
  - 1.9.3
before_script:
  - psql -c 'create database chat_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bundle exec rspec spec
notifications:
  email:
    - alanmulhall@hotmail.com
branches:
  only:
    - master
